
cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      instance-profile: true
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    stack:
      auto: false